### ISSUE TITLE
Can you publish this to NPM?

### ISSUE THREAD

**Issue by jvandyke** [ivpusic/angular-cookie#43]
It'd be great if this was officially published to NPM.

Quick how to: https://gist.github.com/coolaj86/1318304

**Comment by ivpusic** [comment]
This is client side package, and I think it is more natural to be publised only on bower.

**Comment by jvandyke** [comment]
Being that Angular itself is published on NPM along with all of its optional modules (https://www.npmjs.com/~angularcore) and the NPM maintainers themselves have blessed (http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) and are making efforts to improve client code support, I think this is a reasonable request.

Of course, it's your repo, so you don't have to. I'm pulling it from the address directly, so it doesn't matter too much. Publishing just allows you to have an official build before someone else publishes it or takes the angular-cookie name for a different project.
