### ISSUE TITLE
Using angular-cookie to share cookies across domains

### ISSUE THREAD

**Issue by c0debreaker** [ivpusic/angular-cookie#45]
I have 2 AngularJS applications running on my localhost. I haven't transferred it yet to a real domain.

Am I right that if I set domain on both applications to localhost, angular-cookie should be able to share the cookies to my 2 applications?

**Comment by yunderboy** [comment]
Yeah, I've encountered the same problem.
Let me know if you figure out a way to solve the issue! I'd really appreciate it!

Sicerely

**Comment by c0debreaker** [comment]
Yup, just set your domain and not the FQDN.

For example

.microsoft.com

Notice, I didn't include the host before the domain. So any app in .microsoft.com domain will be able to use that same cookie.
