### ISSUE TITLE
Add this repo to npm too please

### ISSUE THREAD

**Issue by riggerthegeek** [ivpusic/angular-cookie#54]
Hi there

I've fallen a little bit in love with Browserify recently.  I find this package incredible useful (thank you) and it's a little bit irritating having to faff about pulling it in with bower.

Can you add this into npm so that I can use it with Browserify?  Pretty please.

Thanks

S

**Comment by Anahkiasen** [comment]
:+1:

**Comment by heston** [comment]
I just opened a PR that makes it easier to use `angular-cookie` with webpack and browserify. Publishing to npm would be pretty trivial after this: https://github.com/ivpusic/angular-cookie/pull/61

**Comment by ivpusic** [comment]
Done.
